# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json  
name: cicd

on:
  push:
    tags: [ "v**" ]
  
defaults:
  run:
    shell: sh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install deps
        run: yarn install

      - name: Build
        run: yarn build

      - name: Save package artifact
        uses: "actions/upload-artifact@v3"
        with:
          name: "package.zip"
          path: "package.zip"